USE [master]
GO

/****** Object:  Database [Db_4]    Script Date: 8/16/2022 11:35:19 PM ******/
CREATE DATABASE [Db_4]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Db_4', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Db_4.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Db_4_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Db_4_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Db_4].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Db_4] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Db_4] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Db_4] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Db_4] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Db_4] SET ARITHABORT OFF 
GO

ALTER DATABASE [Db_4] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Db_4] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Db_4] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Db_4] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Db_4] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Db_4] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Db_4] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Db_4] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Db_4] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Db_4] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Db_4] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Db_4] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Db_4] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Db_4] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Db_4] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Db_4] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Db_4] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Db_4] SET RECOVERY FULL 
GO

ALTER DATABASE [Db_4] SET  MULTI_USER 
GO

ALTER DATABASE [Db_4] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Db_4] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Db_4] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Db_4] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Db_4] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Db_4] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Db_4] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Db_4] SET  READ_WRITE 
GO

